name: 'Testing2'

on:
  workflow_dispatch:
    inputs:
      artifact_id:
        required: true
        type: string


jobs:
  testing2:
    name: 'testing2'
    runs-on: ubuntu-latest


    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/github-script@v5
      id: set-result
      env:
        artifact_id: ${{ inputs.artifact_id }}
      with:
        result-encoding: string
        debug: true
        script: |
          const https = require('https');
          const fs = require('fs');
          var artifact_id = process.env.artifact_id || 'unset'
          const download = await github.rest.actions.downloadArtifact({
            owner: 'checkitsam',
            repo: 'action-testing',
            artifact_id: artifact_id,
            archive_format: 'zip'
          });
          const file = fs.createWriteStream("artifact.zip");
          const request = https.get(download.url, function(response) {
            response.pipe(file);
          });


    - name: List and cat
      run: ls -lt && unzip artifact.zip && cat test
