name: 'Testing2'

on:
  push:

jobs:
  testing2:
    name: 'testing2'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/github-script@v5
      id: set-result
      with:
        result-encoding: string
        debug: true
        script: |
          github.rest.actions.downloadArtifact({
            owner: 'checkitsam',
            repo: 'action-testing',
            artifact_id: '161667560',
            archive_format: 'zip'
          });

    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"

    - name: List and cat
      run: ls -lt && cat test
